### ISSUE TITLE
Mir2Gene database down ?

### ISSUE THREAD

**Issue by notetienne** [xia-lab/miRNetR#1]
Hello,

When calling for QueryMultiListMir() it seems that the mir2gene database is down

> In download.file(db.path, db.name, mode = "wb") :
>   cannot open URL 'https://www.xialab.ca/resources/mirnet/mir2gene.sqlite': HTTP status was '404 Not Found'

**Comment by le-chang** [comment]
Hello,
Thanks for your patience. The issue has been fixed. 
The database can be downloaded from: "https://dev.mirnet.ca/miRNet/resources/sqlite/mir2gene.sqlite"
Please reinstall the miRNetR package and follow the vignettes to perform the analysis.
