### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yalbibalderas** [xia-lab/miRNetR#2]
Hi,
I have been using your web app, it has been very helpful. Now I realized that you have created this package so I try to follow the pipeline, however, it is not clear to me where I can find the results of the different miRNAs' targets, e.g., in the pipeline you use this function

SetupMirListData(mirs = "hsa-mir-101-3p
hsa-mir-133b
hsa-mir-147a
hsa-mir-3140-3p
hsa-mir-361-5p
hsa-mir-510-5p", orgType = "hsa", idType = "mir_id", tissue = "Kidney")

However, the results table and the network is recovering only targets for the first miRNA
Thanks in advance,

**Comment by le-chang** [comment]
Hello,
Sorry about the issue. It was due to a recent update in the database. 
The issue has been fixed now. Please reinstall the package and try to perform the analysis again.
Feel free to send me an email if you have other questions: le.chang@mail.mcgill.ca
Thanks,
Le
