### ISSUE TITLE
report errors

### ISSUE THREAD

**Issue by bothan-golden** [xia-lab/miRNetR#3]
> QueryMultiListMir()
[1] "Downloading https://dev.mirnet.ca/miRNet/resources/sqlite/mir2gene.sqlite"
试开URL’https://dev.mirnet.ca/miRNet/resources/sqlite/mir2gene.sqlite'
Error in download.file(db.path, db.name, mode = "wb") : 
  无法打开URL'https://dev.mirnet.ca/miRNet/resources/sqlite/mir2gene.sqlite'
此外: Warning message:
In download.file(db.path, db.name, mode = "wb") :
  InternetOpenUrl失败:’无法与服务器建立连接

**Comment by le-chang** [comment]
Hello,
Thanks for reporting the error. Unfortunately, we are not able to replicate the issue.
You may want to directly download the SQLite database using this [link](https://drive.google.com/file/d/1eqZdn9nDQZGPfKr7v_G-UQDFncliGDGo/view?usp=sharing)
Please feel free to send me an email if you have other questions: le.chang@mail.mcgill.ca
Le
