### ISSUE TITLE
Database error - miRNA to gene mapping

### ISSUE THREAD

**Issue by robinredX** [xia-lab/miRNetR#4]
Hi, I am using expression tables of miRNA (mus). I get the following error with `PerformMirGeneMapping()` -

`PerformMirGeneMapping()`
`[1] "Downloading https://dev.mirnet.ca/miRNet/resources/sqlite/mir2gene.sqlite"
trying URL 'https://dev.mirnet.ca/miRNet/resources/sqlite/mir2gene.sqlite'
Error in download.file(db.path, db.name, mode = "wb") : 
  cannot open URL 'https://dev.mirnet.ca/miRNet/resources/sqlite/mir2gene.sqlite'
In addition: Warning message:
In download.file(db.path, db.name, mode = "wb") :
  cannot open URL 'https://dev.mirnet.ca/miRNet/resources/sqlite/mir2gene.sqlite': HTTP status was '404 Not Found'`

**Comment by le-chang** [comment]
Hello,
Thanks for reporting the error. The issue has been fixed.
The database can now be downloaded from "https://www.xialab.ca/resources/sqlite/mir2gene.sqlite"
Please reinstall the miRNetR package and try again.
Let me know if you have other questions.
