### ISSUE TITLE
Enrichment Analysis

### ISSUE THREAD

**Issue by dwill023** [xia-lab/miRNetR#5]
Hi, I'm trying to use the PerformMirTargetEnrichAnalysis to get the pathways for my microRNA targets. I followed the steps 1-7 on your vignette [3.1.2 Mapping to multiple targets](https://www.mirnet.ca/miRNet/docs/_html_miRNetR_tutorial.html#mapping-to-multiple-targets) but when I change the default fun.type = "func" to "kegg" or "reactome" I get the error shown below.

```
PerformMirTargetEnrichAnalysis(
  adjust.type = "NA",
  fun.type = "kegg",
  file.nm = "network_enrichment_func_1",
  IDs = diff_mirs,
  algo = "hyp"
)
```

Error in data.frame(Pathway = rownames(res.mat), res.mat, stringsAsFactor = F) : 
  arguments imply differing number of rows: 0, 1
In addition: Warning message:
In colnames(dataSet$mir.filtered) == c("Name1", "ID1", "Name2",  :
  longer object length is not a multiple of shorter object length

I do not get a result like I do when I use `fun.type = "func" `

Please advise, Thanks!

**Comment by le-chang** [comment]
Hello,

Thanks for reporting the issue.

Please note, "kegg" and "reactome" are for miRNA target gene enrichment analysis. Therefore, the input must contain **gene** IDs. 

See this example from the vignette, where IDs = "DDX3X; ELOVL4; ACAT1; HAPLN1..."
`PerformMirTargetEnrichAnalysis(
  adjust.type = "NA",
  fun.type = "kegg",
  file.nm = "network_enrichment_kegg_1",
  IDs = "DDX3X; ELOVL4; ACAT1; HAPLN1; MEGF9; FMR1; IL12A; OLR1; RNF6; SOD3; MRAP2", 
  algo = "hyp"
)` 

When you use `fun.type = "func"`, this is for miRNA function set enrichment analysis, the input must be miRNAs.

Hope this helps. Let me know if you have other questions.
