### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by cebercoto** [xia-lab/miRNetR#6]
Cannot install mirnetR following the commands with the following output:

> devtools::install_github("xia-lab/miRNetR", build = TRUE, build_opts = c("--no-resave-data", "--no-manual"), build_vignettes = TRUE, force = TRUE)
Downloading GitHub repo xia-lab/miRNetR@HEAD
Skipping 5 packages not available: genefilter, HTqPCR, edgeR, limma, preprocessCore
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────✔  checking for file ‘/tmp/RtmpTiqGqn/remotesd9a9232970dfb/xia-lab-miRNetR-1f28123/DESCRIPTION’ ...
─  preparing ‘miRNetR’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
         -----------------------------------
─  installing *source* package ‘miRNetR’ ...
   ** using staged installation
   ** R
   ** byte-compile and prepare package for lazy loading
   ** help
   *** installing help indices
   ** building package indices
   ** installing vignettes
   ** testing if installed package can be loaded from temporary location
   Error: package or namespace load failed for ‘miRNetR’ in namespaceExport(ns, exports):
    undefined exports: GetRandomMirTargetGenes, GetRandomXenoMirTargetGenes, LoadClusterLib, LoadDiseaseLib, LoadFuncLib, LoadGOLib, LoadHMDDLib, LoadKEGGLib, LoadREACTOMELib, LoadTFLib, LoadTissueLib, LoadmiRFamLib
   Error: loading failed
   Execution halted
   ERROR: loading failed
─  removing ‘/tmp/RtmpEZ0XG9/Rinstd9d7a242c5f76/miRNetR’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'miRNetR' from GitHub:
  ! System command 'R' failed

All the previous steps don't produce any errors

Thanks

**Comment by fiyhui** [comment]
Hello! The issue should be fixed now. 
Please try again and don't hesitate to contact us if you still see the error.

**Comment by cebercoto** [comment]
Hi! many thanks I was able to install it now. but now it is saying:

> library(miRNetR)
> Init.Data("mir", "mirlist")
Error in Init.Data("mir", "mirlist") : 
  could not find function "Init.Data"

can you look into this?
FYI, I was already a user for quite some time, not that I am new to mirnetR :)

Thanks

**Comment by cebercoto** [comment]
Hi again, I'm guessing there are things going on since the error has changed now after reinstallation of the R package (just FYI in case it helps):

> Init.Data("mir", "mirlist")
Error in Init.Data("mir", "mirlist") : object '.on.public.web' not found

Cheers

**Comment by fiyhui** [comment]
Good day! Thank you for the feedback, it's much appreciated. Indeed, we are aiming to push an update in the R code to solve this issue by the end of the week. In the meantime, feel free to install a previous commit - the last commit version from 2022 will be more stable.

**Comment by cebercoto** [comment]
Thanks! yes, indeed I did an upgrade of R version recently and reinstalled all packages, hence all my problems. The last version of 2022 is working fine now. Any idea of when the new version will be "stable"? will it be announced somewhere?

Many thanks!

**Comment by fiyhui** [comment]
Hi! The recent updates are mostly for improving web interface and user experience, there is no major changes to R functionality. If we do a major update, it will for sure be announced on the miRNet webpage.

**Comment by cebercoto** [comment]
Perfect! many thanks. and thanks for all the hard work!
